### ISSUE TITLE
Gravity example

### ISSUE THREAD

**Issue by Matiiss** [Matiiss/pygame_examples#18]
Simple example, no collisions involved, just gravity, for example, make some red ball fall, it could be for example spawned by mouse click.

Implementing acceleration here is the most crucial detail.

**Comment by pycoinfu** [comment]
hey there, i'm working on this issue

**Comment by pycoinfu** [comment]
fixed the issue #21

**Comment by blankRiot96** [comment]
> fixed the issue #21 (PR got merged)

Linked PR was merged, closing issue
