### ISSUE TITLE
Maze generation example

### ISSUE THREAD

**Issue by blankRiot96** [Matiiss/pygame_examples#51]
Description:
To produce a maze at once, or periodically 
I imagine a tile based maze, that uses an algorithm(or peeling noise?) to get valid "passable" mazes, so that there is always a path to the end.

**Comment by oddbookworm** [comment]
Is using Cellular Automata too complicated for this one? If not, I might try my hand at it

**Comment by Matiiss** [comment]
No joke, could implement maze generation from Scratch (like... the language not _from nothing_): https://www.youtube.com/watch?v=22Dpi5e9uz8

**Comment by oddbookworm** [comment]
I'll take this one
