### ISSUE TITLE
Procedual Generation

### ISSUE THREAD

**Issue by ScriptLineStudios** [Matiiss/pygame_examples#75]
Procedural World generation using some kind of noise, (perlin, simplex) Could also be extended with a very simple biome generation system or island generation. End result looking something like this: 
![image](https://user-images.githubusercontent.com/85095943/174302557-f37b14c9-9987-49f1-b1a9-e3e77113a5ff.png)

**Comment by pycoinfu** [comment]
#76 got merged, closing the issue
